name: Integration Tests

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  integration-test:
    name: Integration tests (microk8s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: latest/stable
          provider: microk8s
      - name: Run integration tests
        run: tox -vve integration